file_load:
  model_name: qwen2-1.5b
  #model_path: /home/liangshuqiao/models/Qwen2.5-14B-Instruct #模型文件路径
  # model_path: /home/liangshuqiao/models/qwen3-8b #模型文件路径
  model_path: /home/liangshuqiao/models/qwen-1.5 #模型文件路径
  # model_path: /home/liangshuqiao/models/DeepSeek-R1-Distill-Qwen-7B #模型文件路径
  dataset_path: dataset/PsyDTCorpus/PsyDTCorpus_train_mulit_turn_packing.json #数据集文件路径
  use_eval: True #是否启用评估
  eval_dataset_path: dataset/PsyDTCorpus/PsyDTCorpus_test_single_turn_split.json #验证集文件路径
  # test_size: 0.2 #验证集占数据集占比：0~1
  split_way: train #数据集分割方式
  lora_output_path: output
  save_model_path: model_output/qwen2-1.5b
  # gguf_path: model_output/qwen2_14b_all_lora_gguf
  logging_path: trainlog
  # shuffle: True

#系统级提示词
system_prompt: |
  """
  你是一个医美客服，你需要在多轮对话场景中识别用户场景,目前的场景为：{scence}
  经过深思熟虑之后给出简短有力而亲切的回答，思考和回答的时间越短越好，最好是一句话
  """


